### PR TITLE
Create a simple one-page website from README.md

### PR DESCRIPTION
**Pull request by davidsneighbour**
... so this can be hosted somewhere. I can add Netlify setup if it's going to be hosted here. This is WIP for #41.

### CODE REVIEW

**Comment by budparr** [comment]
Nice. Will this retain the current README?

**Comment by davidsneighbour** [comment]
Yes. all changes stay in the README and hugo takes it and makes a one page homepage.

**Comment by davidsneighbour** [comment]
I only need to go over some things with titles and images and add some nice design. It was astonishing easy :)

**Comment by budparr** [comment]
awesome!. I can host it on my netlify account

**Comment by budparr** [comment]
Are you in our TND Slack? https://slack.tnd.dev

**Comment by davidsneighbour** [comment]
> awesome!. I can host it on my netlify account

Then I'll add my Netlify scripts for some optimization. I'll go over the design tomorrow. If you have any preferences let me know here. I think Bootstrap with a nice font and some dynamic navigation that stays within the view port.

**Comment by davidsneighbour** [comment]
bump

**Comment by budparr** [comment]
Oh, hey. Wow, I completely missed this. I'll set up Netlify and get it running.

**Pull request merged**
